server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://user:123@peer2:8762/eureka/,http://user:123@peer3:8763/eureka/
spring:
  application:
    name: EUREKA-HA
  profiles:
    active: peer1

    # 开启安全配置
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123
